### ISSUE TITLE
'CarplateConfig' object has no attribute 'IMAGE_META_SIZE'

### ISSUE THREAD

**Issue by jingwang960108** [anonymoussss/Cascade-Mask-RCNN#2]
When I run carplate.py
Traceback (most recent call last):
  File "carplate.py", line 332, in <module>
    model_dir=args.logs)
  File "D:\Cascade-Mask-RCNN-master\ceshi\mrcnn\model.py", line 2310, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "D:\Cascade-Mask-RCNN-master\ceshi\mrcnn\model.py", line 2330, in build
    input_image_meta = KL.Input(shape=[config.IMAGE_META_SIZE],
AttributeError: 'CarplateConfig' object has no attribute 'IMAGE_META_SIZE'

**Comment by anonymoussss** [comment]
Please check whether your code correctly inherits the Config class in config.py (https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/config.py). Note that my repository did not upload the unchanged py file in the original Matterport repository.

**Comment by jingwang960108** [comment]
> Please check whether your code correctly inherits the Config class in config.py (https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/config.py). Note that my repository did not upload the unchanged py file in the original Matterport repository.

thinks,with your help, this problem has been solved.
